### ISSUE TITLE
Browser tests stopped working for the latest release of Meteor

### ISSUE THREAD

**Issue by SenadZaimovic** [Meteor-Community-Packages/meteor-browser-tests#31]
After upgrading the Meteor project from 1.11.1 to 1,12.1 browser tests using the puppeteer driver have stopped working. 

They hang on start with only stderr:

> I20210112-11:16:17.959(0)? --------------------------------
I20210112-11:16:17.959(0)? ----- RUNNING CLIENT TESTS -----
I20210112-11:16:17.960(0)? --------------------------------
 Started your app.

 App running at: http://localhost:9000
I20210112-11:16:19.684(0)? HeadlessChrome/88.0.4298.0
W20210112-11:16:21.908(0)? (STDERR)
W20210112-11:16:22.308(0)? (STDERR) waitFor is deprecated and will be removed in a future release. See https://github.com/puppeteer/puppeteer/issues/6214 for details and how to migrate your code.

I have tried multiple versions of puppeteer.

**Comment by jankapunkt** [comment]
@SenadZaimovic  do you have HMR active?

**Comment by jankapunkt** [comment]
I am not sure if this will fix your issue but I provided a patch here: #33

**Comment by StorytellerCZ** [comment]
@SenadZaimovic did #33 fix your issue?

**Comment by bessw** [comment]
I had the same problem and after updating to a version containing this patch it was solved.

Thanks for your fix 👍
