### ISSUE TITLE
Playwright not terminating when client tests are done

### ISSUE THREAD

**Issue by Torgen** [Meteor-Community-Packages/meteor-browser-tests#43]
Tried the new playwright browser driver with my app (https://github.com/Torgen/codex-blackboard in the `playwright` branch) and the client tests run, but the process never terminates. I'm running ubuntu 20.04 on WSL2, but my github actions runs have the same issue; the test command is `TEST_BROWSER_DRIVER=playwright meteor npm run test`.

**Comment by StorytellerCZ** [comment]
@hexsprite can you take a look

**Comment by hexsprite** [comment]
Yeah, I can confirm there is a problem. It looks like a conflict with Meteor's Promise implementation. I will have to create a bug report in the Meteor repo for this. Seems like this makes the playwright testing backend unusable at the moment...

**Comment by Torgen** [comment]
I tested this on my app, and while it terminated after running the unit tests, it still didn't terminate after full app tests.

**Comment by StorytellerCZ** [comment]
Let's create another issue for it.

**Comment by hexsprite** [comment]
@Torgen I am using the full app tests by default and it's working fine both when running locally and in CI. Does it happen in a fresh project with a minimal reproduction?
