### ISSUE TITLE
Playwright not terminating after client tests in full-app mode.

### ISSUE THREAD

**Issue by Torgen** [Meteor-Community-Packages/meteor-browser-tests#47]
https://github.com/Torgen/codex-blackboard in the `playwright` branch on both WSL2 Ubuntu and Github Actions freezes after printing the number of client test cases passed, but before saying "All tests finished!" when you run `TEST_BROWSER_DRIVER=playwright meteor npm run test.full`. It doesn't happen under puppeteer. I don't have a minimal reproduction yet, unfortunately.

**Comment by StorytellerCZ** [comment]
Originally reported in #43
